<template>
  <iframe
    src="https://ghbtns.com/github-btn.html?user=mattjcowan&repo=foxvalleymeetup-aspnet-signalr-nuxtjs&type=star&count=true"
    frameborder="0"
    scrolling="0"
    width="100px"
    height="20px"
  />
</template>
